web:
  build: .
  ports:
   - "3000:3000"
  environment:
    - PORT=3000
    - NODE_ENV=development
    - NODE_MONGODB_URL=mongodb:27017
    - NODE_MONGODB_DATABASE_NAME=history-service
    - ANALYTICS_EVENT_ENABLED=true
    - ANALYTICS_EVENT_HOST=circuitBreakerAnalytics
    - ANALYTICS_EVENT_PORT=3001
    - DEBUG=history-service:*
  links:
    - mongodb:mongodb
    - circuitBreakerAnalytics:circuitBreakerAnalytics
circuitBreakerAnalytics:
  image: jasonmichels/circuit-breaker-analytics
  ports:
   - "3001:3001"
  environment:
    - PORT=3001
    - NODE_ENV=development
    - NODE_MONGODB_URL=mongodb:27017
    - NODE_MONGODB_DATABASE_NAME=circuit-breaker-analytics
mongodb:
  image: tutum/mongodb
  ports:
   - "27017:27017"
   - "28017:28017"
  environment:
    - AUTH=no